# make clean
#   Remove all potential generated folder/files
#
# make doc
#   Generate doxygen documentation in doc
# make update_doc
#   Update generated documentation (path to local git repository is specified in variable `DOC_PATH`)
#
# make test
#   Check test cases
#
# make venv
#   Create python virtual environnement
#
# Required dependencies:
# - doc: doxygen
# - test: pytest (Python package, listed in requirements.txt)
# - venv: virtualenv
#
DOC_PATH=../CNR-Engineering.github.io/TelTools

doc: doxygen.config
	doxygen $<

update_doc: doc
	rm -r ${DOC_PATH} && cp -r doc/html ${DOC_PATH}
	cd ${DOC_PATH} && git add -A && git commit -m "Update doc" && git pull && git push && cd -

venv:
	virtualenv venv --python=python3
	source venv/bin/activate && pip install -r requirements.txt --upgrade

test:
	pytest tests -v

# .cache (generated by pytest)
clean:
	rm -rf doc venv .cache

.PHONY: clean test update_doc venv
